version: 2.1
description: |
  Build a Docker application and push to an ECR repository.

executors:
  helm-executor:
    docker:
      - image: 'circleci/python:3'

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
  custom-orb: liatrio-poc/circleci-orb-poc@0.1.2
  
workflows:
  kotlin-application:
    jobs:
      - custom-orb/gradle-test:
          executor: custom-orb/gradle-executor
          cache_checksum_file: build.gradle.kts
          reports_path: build/reports/
          test_results_path: build/test-results/
      #- custom-orb/build-push-docker-image:
      #    executor: aws-ecr/default
      #    repo-name: $AWS_REPO
      #    requires:
      #     - custom-orb/gradle-test
      #- custom-orb/deploy-helm-chart:
      #    app-name: spring-boot-kotlin
      #    cluster-name: circleci-pipeline-poc
      #    requires:
      #     - custom-orb/build-push-docker-image
