version: 2.1
description: |
  Build a Docker application and push to an ECR repository.

executors:
  helm-executor:
    docker:
      - image: 'circleci/python:3'

orbs:
  gradle: circleci/gradle@2.2.0
  aws-cli: circleci/aws-cli@2.0.2
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-eks: circleci/aws-eks@0.2.3
  kubernetes: circleci/kubernetes@0.4.0
  helm: circleci/helm@1.2.0
  custom-orb: liatrio-poc/circleci-orb-poc@dev:2b071ad
  
workflows:
  kotlin-application:
    jobs:
      - custom-orb/gradle-test:
          executor: custom-orb/gradle-executor
          cache_checksum_file: build.gradle.kts
          reports_path: build/reports/
          test_results_path: build/test-results/
      - custom-orb/build-push-docker-image:
          executor: aws-ecr/default
          repo-name: $AWS_REPO
          requires:
           - custom-orb/gradle-test
      - custom-orb/deploy-helm-chart:
          app-name: spring-boot-kotlin
          cluster-name: circleci-pipeline-poc
          requires:
           - custom-orb/build-push-docker-image
