version: 2.1
description: |
  Build a Docker application and push to an ECR repository.

executors:
  helm-executor:
    docker:
      - image: 'circleci/python:3'

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
  custom-orb: liatrio-poc/circleci-orb-poc@0.0.8

jobs:
  upload-artifact:
    docker:
      - image: circleci/openjdk:8-jdk
        auth:
          username: cwai96
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/repo
    steps:
      - checkout
      - run: mvn dependency:go-offline
      - run:
          name: Maven Build
          command: |
            mvn clean install
      - run:
          name: Install JFrog CLI
          command: curl -fL https://getcli.jfrog.io | sh
      - run: 
          name: Push to Artifactory
          command: |
              ./jfrog config add calvin-server-config --artifactory-url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey password --interactive=false
              
  
workflows:
  kotlin-application:
    jobs:
      - custom-orb/gradle-test:
          executor: custom-orb/gradle-executor
          cache_checksum_file: build.gradle.kts
          reports_path: build/reports/
          test_results_path: build/test-results/
      - upload-artifact
      # - custom-orb/build-push-docker-image:
      #     executor: aws-ecr/default
      #     repo-name: $AWS_REPO
      #     requires:
      #      - custom-orb/gradle-test
      # - custom-orb/deploy-helm-chart:
      #     app-name: spring-boot-kotlin
      #     cluster-name: circleci-pipeline-poc
      #     requires:
      #      - custom-orb/build-push-docker-image
  
